import { getSession } from "@/lib/auth";
import { getActiveLocationId } from "@/lib/location";
import { can } from "@/lib/rbac";
import { rangeFor, type PeriodKey } from "@/lib/period";
import { getDashboard } from "@/lib/reports";
import { generateInsights } from "@/lib/ai";
import { Card, PageHeader, Badge, EmptyState, Icon } from "@/components/ui";
import PeriodSelect from "@/components/PeriodSelect";

export const dynamic = "force-dynamic";

export default async function InsightsPage({
  searchParams,
}: {
  searchParams: Promise<{ period?: string }>;
}) {
  const session = (await getSession())!;
  if (!can(session.role, "viewProfit")) {
    return <Card className="p-8"><EmptyState icon="lock" title="No access" hint="Your role can't view insights." /></Card>;
  }
  const sp = await searchParams;
  const period = (sp.period as PeriodKey) || "mtd";
  const range = rangeFor(period);
  const loc = await getActiveLocationId();

  const data = await getDashboard(range, loc);
  const { source, insights } = await generateInsights(data);

  const toneStyle: Record<string, { card: string; icon: string; color: string }> = {
    positive: { card: "border-secondary/40", icon: "trending_up", color: "text-secondary" },
    warning: { card: "border-tertiary/40", icon: "warning", color: "text-tertiary" },
    neutral: { card: "border-outline-variant/60", icon: "lightbulb", color: "text-primary" },
  };

  return (
    <div>
      <PageHeader
        title="AI Insights"
        subtitle={`Automated analysis · ${range.label}`}
        actions={<PeriodSelect value={period} />}
      />

      <div className="flex items-center gap-2 mb-4">
        {source === "ai" ? (
          <Badge tone="info"><Icon name="auto_awesome" className="text-[14px]" /> Generated by Claude</Badge>
        ) : (
          <Badge tone="neutral">Rule-based analysis</Badge>
        )}
        {source === "rules" && (
          <span className="text-body-sm text-on-surface-variant">
            Set <span className="font-mono">ANTHROPIC_API_KEY</span> to enable AI-written insights.
          </span>
        )}
      </div>

      {insights.length === 0 ? (
        <Card className="p-8"><EmptyState icon="auto_awesome" title="Not enough data yet" hint="Record some sales to generate insights." /></Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {insights.map((i, idx) => {
            const s = toneStyle[i.tone] ?? toneStyle.neutral;
            return (
              <Card key={idx} className={`p-5 ${s.card}`}>
                <div className="flex items-start gap-3">
                  <div className="w-9 h-9 rounded-md bg-surface-container flex items-center justify-center flex-shrink-0">
                    <Icon name={s.icon} className={`text-[20px] ${s.color}`} />
                  </div>
                  <div>
                    <h3 className="font-semibold text-on-surface">{i.title}</h3>
                    <p className="text-body-md text-on-surface-variant mt-1">{i.detail}</p>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
